name: Deploy WordPress

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t west_wordpress .

    - name: Run Docker container
      run: docker run --name wordpressapp -d -p 80:80 wordpress